spring.application.name=MainAPI
spring.kafka.bootstrap-servers= localhost:9092
server.port=8080

feign.client.config.default.connectTimeout=10000
feign.client.config.default.readTimeout=10000
feign.client.config.default.retryer=feign.Retryer.NEVER_RETRY


